framework:
  messenger:
    failure_transport: failed

    transports:
      # Transport asynchrone pour envoyer les messages (notamment les emails)
      async:
        dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
        options:
          use_notify: true
          check_delayed_interval: 60000
        retry_strategy:
          max_retries: 5 # Augmentation du nombre de tentatives de réessai à 5
          delay: 1000 # Délai initial de 1 seconde entre les tentatives
          multiplier: 2 # Le délai double à chaque tentative échouée
          max_delay: 60000 # Délai maximum de 60 secondes entre les tentatives
      failed: "doctrine://default?queue_name=failed" # Transport des messages échoués

    default_bus: messenger.bus.default

    buses:
      messenger.bus.default: []

    routing:
      Symfony\Component\Mailer\Messenger\SendEmailMessage: async
      Symfony\Component\Notifier\Message\ChatMessage: async
      Symfony\Component\Notifier\Message\SmsMessage: async
