security:
  # Gestion du hachage des mots de passe
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"

  # Fournisseur d'utilisateurs basé sur l'entité User
  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  firewalls:
    # Désactiver la sécurité pour certaines routes de développement
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    # Firewall principal pour gérer les utilisateurs
    main:
      lazy: true
      provider: app_user_provider

      # Formulaire de connexion
      form_login:
        login_path: app_login
        check_path: app_login
        enable_csrf: true
        default_target_path: app_meeting_index

      # Déconnexion
      logout:
        path: app_logout
        target: app_login

      # Activation de la mémorisation de l'utilisateur (Remember Me)
      remember_me:
        secret: "%kernel.secret%"
        lifetime: 604800
        path: /
        always_remember_me: false

  # Règles de contrôle d'accès
  access_control:
    - { path: ^/contact, roles: PUBLIC_ACCESS }
    - { path: ^/cookies, roles: PUBLIC_ACCESS }
    - { path: ^/login, roles: PUBLIC_ACCESS }
    - { path: ^/admin, roles: ROLE_ADMIN }
    - { path: ^/meeting, roles: ROLE_USER }
    - { path: ^/user, roles: IS_AUTHENTICATED_FULLY }
