security:
  # Gestion du hachage des mots de passe
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"

  # Fournisseur d'utilisateurs basé sur l'entité User
  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  firewalls:
    # Désactiver la sécurité pour certaines routes de développement
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    # Firewall principal pour gérer les utilisateurs
    main:
      lazy: true
      provider: app_user_provider

      # Formulaire de connexion
      form_login:
        login_path: app_login # La route de connexion
        check_path: app_login # La route pour vérifier les identifiants
        enable_csrf: true # Activer la protection CSRF pour le formulaire de connexion
        default_target_path: app_meeting_index # Redirection après connexion réussie vers la page des réunions

      # Déconnexion
      logout:
        path: app_logout # Route de déconnexion
        target: app_login # Redirection après déconnexion vers la page de connexion (ou vers une page publique)

      # Activation de la mémorisation de l'utilisateur (Remember Me)
      remember_me:
        secret: "%kernel.secret%"
        lifetime: 604800 # Durée de vie de la session en secondes (1 semaine)
        path: /
        always_remember_me: false # Ne mémoriser l'utilisateur que si l'option est activée explicitement

  # Règles de contrôle d'accès pour différentes sections du site
  access_control:
    - { path: ^/admin, roles: ROLE_ADMIN } # Accès restreint aux administrateurs
    - { path: ^/meeting, roles: ROLE_USER } # Accès aux réunions pour les utilisateurs authentifiés
    - { path: ^/user, roles: IS_AUTHENTICATED_FULLY } # Accès aux pages utilisateur pour les utilisateurs authentifiés
    - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY } # La page de login doit être accessible uniquement aux anonymes
